name: Checks

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - '*'

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 16.x

      - name: Install
        run: npm ci
      
      - name: Lint
        run: npm run lint

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: Coverage report
        uses: codecov/codecov-action@v1
